# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://docs.hugoblox.com/reference/language/

# Default language
en:
  languageCode: en-us
  languageName: English
  contentDir: content
  # Uncomment for multi-lingual sites, and move English content into `en` sub-folder.
  #contentDir: content/en

# Uncomment the lines below to configure your website in a second language.
zh:
  languageCode: zh-Hans
  languageName: 中文
  contentDir: content
  title: Shaojian Yang
  params:
    description: 杨劭坚的个人学术主页。
  menu:
    main:
      - name: 简介
        url: '#about'
        weight: 10
      - name: 博文
        url: '#posts'
        weight: 20
      - name: 论文与专利
        url: '#featured'
        weight: 30
      - name: 足迹
        url: '/zh/footprints/'
        weight: 35
      - name: 联系
        url: '#contact'
        weight: 40
